StereoBM minimum Block Size set to 5 as required by OpenCV source code.
It was throwing when taking slider all the way to 3:
"cv2.error: OpenCV(4.11.0) /io/opencv/modules/calib3d/src/stereobm.cpp:1190: error: (-211:One of the arguments' values is out of range)
SADWindowSize must be odd, be within 5..255 and be not larger than image width or height in function 'compute'"